stages:
  - build
  - test
  - deploy
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/

build:
  image: node:latest
  stage: build
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint -- --no-fix
    - npm run build
  only:
    - main
    - merge_requests

unit test:
  image: node:latest
  stage: test
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test
  only:
    - main
    - merge_requests

deploy:
  image: electronuserland/builder:wine
  stage: deploy
  script:
    - npm ci --cache .npm --prefer-offline --ignore-scripts
    - npm run build:electron
    - npm run dist -- -wl
  artifacts:
    paths:
      - dist_electron
  only:
    - main
