apiVersion: metrics.polaris-slo-cloud.github.io/v1
kind: CostEfficiencyMetricMapping
metadata:
  namespace: smart-irrigation
  name: irrigation-web-cost-efficiency
spec:
  targetRef:
    kind: Deployment
    name: irrigation-web
    apiVersion: apps/v1
  metricConfig:
    targetThreshold: 500