apiVersion: v1
kind: Namespace
metadata:
  name: smart-irrigation
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: smart-irrigation-ingress
    namespace: smart-irrigation
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: irrigation-web
                port:
                  number: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: smart-irrigation-monitor
  labels:
    k8s-app: smart-irrigation-monitor
    # Needed because of https://github.com/prometheus-operator/prometheus-operator/issues/1470#issuecomment-397500048
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - smart-irrigation
  selector:
    matchLabels:
      application: smart-irrigation
  endpoints:
    - targetPort: 80
      interval: 20s
    - targetPort: 8080
      interval: 20s
